services:
  postgres:
    image: postgres:16
    container_name: annapurna-pg
    environment:
      POSTGRES_DB: annapurna
      POSTGRES_USER: annapurna
      POSTGRES_PASSWORD: annapurna
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./masters.sql:/docker-entrypoint-initdb.d/masters.sql

  minio:
    image: quay.io/minio/minio:latest
    container_name: annapurna-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: annapurna123
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data: